export enum AUTH_ERROR {
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_INCORRECT_PASSWORD = 'AUTH_INCORRECT_PASSWORD',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_ACCOUNT_NOT_CONFIRMED = 'AUTH_ACCOUNT_NOT_CONFIRMED',
  AUTH_INCORRECT_CONFIRMATION_TOKEN = 'AUTH_INCORRECT_CONFIRMATION_TOKEN',
}
